name: vibify
description: An interactive app to just vibe.Stream songs, hear podcasts and enjoy.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  google_fonts: any
  email_validator: ^2.1.17
  animated_notch_bottom_bar: ^1.0.0
  carousel_slider: ^4.2.1
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  image_path: "VibifyIcons/android/play_store_512.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - VibifyIcons/